server:
  port: 8085

eureka:
  instance:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

    prefer-ip-address: true

spring:
  boot:
    message: Hello, Department Service Spring Cloud Bus Demo
