spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/eddy-tech/config-server-repo
          clone-on-start: true
          default-label: master

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8888